name: Create Jira Ticket on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create Jira Ticket
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_USER="${{ github.event.issue.user.login }}"
          GITHUB_ISSUE_ID="${{ github.event.issue.number }}"
          GITHUB_ISSUE_URL="https://github.com/launchiamenterprise/keyrunner/issues/${GITHUB_ISSUE_ID}"
          PRIORITY_ID="2"
          
          curl -X POST \
            --url "$JIRA_URL/rest/api/3/issue" \
            --user "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            --header 'Content-Type: application/json' \
            --data '{
              "fields": {
                "project": {
                  "key": "KR"
                },
                "summary": "'"${ISSUE_TITLE}"'",
                "description": {
                  "version": 1,
                  "type": "doc",
                  "content": [
                    {
                      "type": "paragraph",
                      "content": [
                        {
                          "type": "text",
                           "text": "'"${ISSUE_BODY}"'\n\nGitHub Issue ID: '"${GITHUB_ISSUE_URL}"'"
                        }
                      ]
                    }
                  ]
                },
                "issuetype": {
                  "name": "Bug"
                },
                "priority": {
                  "id":  "'"${PRIORITY_ID}"'"
                }
              }
            }'
